### PR TITLE
Warn when Mutator in directive does not exist

### LINKED ISSUE #3812: Stryker Equality ignore  once not working
image
image

Stryker Version: 
```
"@stryker-mutator/core": "^6.2.3",
"@stryker-mutator/karma-runner": "^6.2.3",
"@stryker-mutator/typescript-checker": "^6.1.2",
```

### PR DESCRIPTION
**Pull request by Giovds**
Closes #3812 

When a directive references an unknown Mutator, log a warning that this directive is not used.

**Mutated code**
```js
const compare = (a, b) => {
  // Stryker disable HelloThere
  // Stryker disable next-line Equality: Wrong Mutator name
  return a - b >= 0 ? 1 : -1;
}

module.exports = { compare };

module.exports = { compare };
```

**Cli**
image

### CODE REVIEW

**Comment by Giovds** [comment]
A couple of questions/issues I still have:
1. I've made the assumption here: https://github.com/stryker-mutator/stryker-js/pull/3842/files#diff-87b4b61b8bd5767c34cf6b141cc3721b722a730e884627e7adc127c8449a07b4R79. Is this correct?
2. It probably is confusing that ignored mutant in the HTML view shows a diff on the comment but has no 'addition line'.
3. It seems that the line number is off by 1. There is a `toBableLine()` method which adds 1 to the line number. Should this be used to re-convert the lines to their original numbers?

**Review by nicojs — CHANGES_REQUESTED** [review]
It is pretty clever to see how you report mutants for unused stryker directives, but I don't think it's a good idea :/. Mutants are mutations in the code, not unused directives. 

I think logging them as a warning is good enough for now. For example, users might want Stryker to fail fast instead of showing them in the report 🤷‍♀️.

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 1]
```diff
@@ -59,12 +64,28 @@ export class DirectiveBookkeeper {
...
+          .map((mutator) => mutator.trim())
+          .filter((mutator) => mutator !== WILDCARD);
+        for (const directive of directives) {
+          if (!allMutators.map((x) => x.name.toLowerCase()).includes(directive.toLowerCase())) {
+            const mutant = new Mutant(directive, originFileName, node, {
+              mutatorName: directive,
+              ignoreReason: `Unused 'Stryker ${directiveType}' directive`,
+              replacement: node,
+            });
+            collector.collect(originFileName, node, mutant, { line: -1, position: 0 }); // Assumption that the directive is always -1 above it...
```
[the remark this answers is not in the document]
Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:79]: Fair point, as I previously mentioned I was misusing them to get them in the report, so that they could get highlighted 🙈 . 

Would you rather inject a logger here, or a function and call it through all the layers? Option 1 probably will log `WARN DirectiveBookkeeper` rather than `WARN Instrumenter`?

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 2]
```diff
@@ -48,8 +53,8 @@ export class DirectiveBookkeeper {
 
   private currentIgnoreRule = rootRule;
 
-  public processStrykerDirectives({ loc, leadingComments }: types.Node): void {
-    leadingComments
+  public processStrykerDirectives(node: types.Node, allMutators: NodeMutator[], collector: I<MutantCollector>, originFileName: string): void {
```
[the remark this answers is not in the document]
Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:56]: 👍

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (nicojs) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:79]: We don't _really_ use the logger categories ATM. I'd be happy with it just being `WARN Instrumenter`. That seems the easiest and straight forward way for now.

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 3]
```diff
@@ -58,6 +64,7 @@ export class DirectiveBookkeeper {
       )
       .filter(notEmpty)
       .forEach(([, directiveType, scope, mutators, optionalReason]) => {
+        this.warnAboutUnusedDirective(mutators, directiveType, scope!);
         const mutatorNames = mutators.split(',').map((mutator) => mutator.trim().toLowerCase());
```
Comment (nicojs) [inline packages/instrumenter/src/transformers/directive-bookkeeper.ts:68]: Please pass this `mutatorNames` to `warnAboutUnusedDirecttive` instead of `mutators`. That way we only split on `,` once.

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 4]
```diff
@@ -89,4 +96,21 @@ export class DirectiveBookkeeper {
...
     return this.currentIgnoreRule.findIgnoreReason(mutatorName, line);
   }
+
+  private warnAboutUnusedDirective(mutators: string, directiveType: string, scope: string) {
+    const directives = mutators
+      .split(',')
+      .map((mutator) => mutator.trim())
+      .filter((mutator) => mutator !== WILDCARD);
+    for (const directive of directives) {
+      if (!this.allMutators.map((x) => x.name.toLowerCase()).includes(directive.toLowerCase())) {
```
Comment (nicojs) [inline packages/instrumenter/src/transformers/directive-bookkeeper.ts:106]: Can we do this `map` in the constructor of this class? Now we're doing it every time we find a directive. 

Its a small performance hit, but mostly this `warn` function shouldn't be doing too much logic.

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 5]
```diff
@@ -89,4 +96,21 @@ export class DirectiveBookkeeper {
...
+        this.logger.warn(
+          // Scope can be global and therefore undefined
+          `Unused 'Stryker ${
+            scope ? directiveType + ' ' + scope : directiveType
+          }' directive. Mutator with name '${directive}' not found. Directive found at: ${this.originFileName}.`
```
Comment (nicojs) [inline packages/instrumenter/src/transformers/directive-bookkeeper.ts:111]: We can use `comment.loc!.start.line` and `comment.loc!.start.column` to also print the location. That would be awesome!

File: packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts [hunk 6]
```diff
@@ -60,7 +65,8 @@ describe('babel-transformer', () => {
       path.replaceWith(types.sequenceExpression([...[...appliedMutants.values()].flatMap((val) => val.expressions), ...path.node.expressions])),
   };
 
-  beforeEach(() => {
+  beforeEach(function () {
+    if (this.currentTest?.title === 'should warn users when a mutator name does not match any of the enabled mutators.') return; // override beforeEach for issue 3812
```
Comment (nicojs) [inline packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts:69]: Please don't ever do this 🙈.

Also: I don't understand why this exclusion for the test is needed. I think the test can work with this before each. There are 2 mutators active here, right?

File: packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts [hunk 7]
```diff
@@ -443,6 +449,35 @@ describe('babel-transformer', () => {
         expect(notIgnoredMutants()).lengthOf(1);
       });
 
+      // issue https://github.com/stryker-mutator/stryker-js/issues/3812
+      it('should warn users when a mutator name does not match any of the enabled mutators.', () => {
+        // Explicitly override the before each because we are interested in the default Mutators
```
Comment (nicojs) [inline packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts:454]: Please add a test per scenario.

File: packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts [hunk 8]
```diff
@@ -443,6 +449,35 @@ describe('babel-transformer', () => {
...
+                return a - b >= 0 ? 1 : -1;
+              }
+            `,
+        });
+        act(ast);
+
+        expect(logger.warn).calledWithMatch(
+          sinon.match("Unused 'Stryker disable' directive. Mutator with name 'SomeOtherThing' not found. Directive found at: example.ts")
+        );
+        expect(logger.warn).calledWithMatch(
```
Comment (nicojs) [inline packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts:476]: Don't forget to add a test where you `expect(logger.warn).not.called`.

**Review by nicojs — CHANGES_REQUESTED** [review]
Looking good! 🤩 , still some stuff left.

File: packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts (hunk 6 above)
Comment (Giovds) [reply packages/instrumenter/test/unit/transformers/babel-transformer.spec.ts:69]: I think I was testing stuff for my original idea were I was exploring some other stuff as well. But you are right I should've removed it afterwards 🙃. I can probably just do with the given scenario.

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts (hunk 5 above)
Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:111]: I probably should have placed a comment for this, but I'll quote the PR description

> I've not included the line number and column since these did not correctly seem to tell where the directive was found, and in case of a next-line directive it had to subtract 1. I think the filename should be sufficient though to find the unused directive. WDYT?

Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:111]: I'll retest and implement the feedback somewhere tomorrow or so.  Thanks!

Comment (nicojs) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:111]: Seems to work fine :) 

image

Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts:111]: Ah there are comment nodes as well, I was looking at the nodes where the mutation is applied. Thanks!

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts (hunk 3 above)
Comment (Giovds) [reply packages/instrumenter/src/transformers/directive-bookkeeper.ts]: Is it OK to show lowercase mutator names, in that case I don't need to split op the assignment to the `mutatorNames`?

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 9]
```diff
@@ -89,4 +100,21 @@ export class DirectiveBookkeeper {
     mutatorName = mutatorName.toLowerCase();
     return this.currentIgnoreRule.findIgnoreReason(mutatorName, line);
   }
+
+  private warnAboutUnusedDirective(mutators: string[], directiveType: string, scope: string, leadingComments: types.Comment[]) {
+    for (const directive of mutators) {
```
Comment (nicojs) [inline packages/instrumenter/src/transformers/directive-bookkeeper.ts:105]: This should be `mutator` instead of `directive`, right?

File: packages/instrumenter/src/transformers/directive-bookkeeper.ts [hunk 10]
```diff
@@ -89,4 +100,21 @@ export class DirectiveBookkeeper {
...
+      if (directive === WILDCARD) continue;
+      if (!this.allMutatorNames.includes(directive.toLowerCase())) {
+        const directiveComment = leadingComments.find((comment) => comment.value.includes(directive));
```
Comment (nicojs) [inline packages/instrumenter/src/transformers/directive-bookkeeper.ts:108]: I think it is better to flow the comment through from the calling side instead of trying to search for it again here.

**Review by nicojs — CHANGES_REQUESTED** [review]
This looks awesome; just a couple of remarks left. Let me know if you need more help.

**Review by nicojs — APPROVED** [review]

**Comment by nicojs** [comment]
Thanks! 🎉
